#Gradle setting
org.gradle.jvmargs=-Xmx6144M
#Minecraft
minecraft_version=1.19.2
support_versions=1.19.2
#Mod
archives_base_name=iammusicplayer
mod_display_name=IamMusicPlayer
mod_version=3.20.0
enabled_platforms=fabric,forge
#Dependencies
architectury_version=6.6.92
fabric_loader_version=0.16.14
fabric_api_version=0.77.0+1.19.2
forge_version=1.19.2-43.5.0
#Mods
mod_menu=4.2.0-beta2
cloth_config=8.3.134
rei=9.2.784
soundphysics_forge=5525251
soundphysics_fabric=5525254
oe_version=3.2.0
#Lavalink
youtube_src=1.13.3
ytdownloader=3.2.8
lava_natives=2.2.3
#Other
felnull_version=1.75