# Gradle
org.gradle.jvmargs=-Xmx6152M
# Environment
minecraft_version=1.21.1
support_versions=1.21.1
enabled_platforms=fabric,neoforge
# Mod
archives_base_name=iammusicplayer_renewed
mod_display_name=IamMusicPlayer_Renewed
mod_version=3.24.0-1.21.1-alpha1
# Dependencies
architectury_version=13.0.8
# mod loader
fabric_loader_version=0.18.4
fabric_api_version=0.116.8+1.21.1
neoforge_version=21.1.219
# mod dependencies
sound_physics_remastered=1.21.1-1.5.1
cloth_config_version=15.0.140
modmenu_version=11.0.3
rei_version=16.0.799
oe_version=3.7.2-1.21.1-beta1
patchouli_version=1.21.1-92
cct_version=1.114.5
sable_companion_version=1.4.2
cca_version=6.1.2
# other
felnull_version=1.75
# lavalink
lava_version_youtube=2.2.4
lavalink=1.16.0
ytdownloader=3.2.8
# Maven Upload
repository_url=https://github.com/Mod-Sauce/IamMusicPlayer_FIX
