name: Mod Build
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: debian
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
<<<<<<< HEAD
          fetch-depth: 200
=======
          fetch-depth: 20
>>>>>>> 3.23.1-1.20.1-mixinfix
      - name: Setup Java 17 & Java 21
        run: |
          sudo apt update
          sudo apt install openjdk-21-jdk
          sudo apt install openjdk-17-jdk
      - name: Build
        run: ./gradlew clean build
