plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "dev.architectury.loom" version "1.13-SNAPSHOT" apply false
}

architectury {
    platformSetupLoomIde()
    neoForge()
}



configurations {
    common
    shadowCommon
    shadowIn
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    modApi "org.modsauce:otyacraftenginerenewed-neoforge:${rootProject.oe_version}"
    modApi "me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rootProject.rei_version}"
    modApi "maven.modrinth:sound-physics-remastered:neoforge-${rootProject.sound_physics_remastered}"

    shadowIn("dev.arbjerg:lavaplayer:${rootProject.lava_version_youtube}") {
        exclude group: 'dev.arbjerg', module: 'lavaplayer-natives'
    }
    shadowIn "com.github.sealedtx:java-youtube-downloader:${rootProject.ytdownloader}"
    shadowIn "dev.felnull:felnull-java-library:${rootProject.felnull_version}"
    shadowIn "com.mpatric:mp3agic:0.9.1"
    shadowIn("dev.lavalink.youtube:v2:${rootProject.lavalink}")
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")

    // relocations here (all your relocate calls)
    mergeServiceFiles {
        relocate 'javax.ws.rs.ext', 'dev.felnull.imp.include.javax.ws.rs.ext'
        relocate 'org.glassfish.jersey.internal.spi', 'dev.felnull.imp.include.org.glassfish.jersey.internal.spi'
    }
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    dependsOn project(":common").tasks.named("sourcesJar")
    from zipTree(project(":common").tasks.named("sourcesJar").get().archiveFile)
}