modLoader = "javafml"
loaderVersion = "47.4.0"
issueTrackerURL = "https://codeberg.org/Mod-Sauce/IamMusicPlayerRenewed/issues"
license = "GNU LGPLv3"

[[mixins]]
config = "iammusicplayer-common.mixins.json"

[[mixins]]
config = "iammusicplayer-neoforge.mixins.json"

[[mods]]
modId = "iammusicplayer"
version = "${version}"
displayName = "Iam Music Player Renewed"
displayURL = "https://mod-sauce.codeberg.page/impr.html"
updateJSONURL = ""
authors = "Us3r0, Shadowbee27"
credits = "Mod-Sauce & contributers, gly091020"
description = '''
Add a boombox that can play music.
The ikisugi music player mod...
'''
#logoFile = "logo.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.iammusicplayer]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "architectury"
mandatory = true
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "cloth_config"
mandatory = true
versionRange = "[15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iammusicplayer]]
modId = "otyacraftenginerenewed"
mandatory = true
versionRange = "[3.7.1,)"
ordering = "NONE"
side = "BOTH"
